version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=E-Commerce
      - MYSQL_USER:'root'
      - MYSQL_PASSWORD:'12345'
      - MYSQL_ROOT_PASSWORD:'12345'
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: